### ISSUE TITLE
when running email search api not correct 

### ISSUE THREAD

**Issue by UzairAhmad89247** [thewhiteh4t/pwnedOrNot#65] opened 2022-09-08 19:54 UTC
when i run a email search it says api key not provided or its not valid even though i have a valid api key

**Comment by thewhiteh4t** [comment] 2022-09-08 23:46
Duplicate of https://github.com/thewhiteh4t/pwnedOrNot/issues/64

**Closed** 2022-09-08 23:47 UTC
